//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetWelds.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WeldId=([0-9]+)")]
        public string WeldIdRegex {
            get {
                return ((string)(this["WeldIdRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vel=([0-9.-]*)")]
        public string VelocityRegex {
            get {
                return ((string)(this["VelocityRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@";FOLD SG?.P_(?:PTP|LIN) ([^,]+), Vel=([0-9]+)[^,]*, Accl=[0-9]+ %, Gun=([0-9X]*), ContCLS=\[([^\]]*)\], ContOPN=\[([^\]]*)\], WeldSchd=([0-9]+), WeldId=([0-9]+), Part=([0-9.]+) mm, Force=([0-9]+) lbs, Eqlzr=([0-9]+), EqRst=([0-9]+) mm, Tool\[([0-9]+)\], Base\[([0-9]+)\], ExtTCP\[([^\]]+)\]")]
        public string KukaWeldNameRegex {
            get {
                return ((string)(this["KukaWeldNameRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Part=([0-9.]+) ")]
        public string WeldThicknessRegex {
            get {
                return ((string)(this["WeldThicknessRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WeldSchd=([0-9]*)")]
        public string WeldScheduleRegex {
            get {
                return ((string)(this["WeldScheduleRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Force=([0-9.]*) ")]
        public string WeldForceRegex {
            get {
                return ((string)(this["WeldForceRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Open_BU1=([^/]]*)/])")]
        public string OpenBackup1Regex {
            get {
                return ((string)(this["OpenBackup1Regex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Open_BU2=([^/]]*)/])")]
        public string OpenBackup2Regex {
            get {
                return ((string)(this["OpenBackup2Regex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Open_BU3=([^/]]*)/])")]
        public string OpenBackup3Regex {
            get {
                return ((string)(this["OpenBackup3Regex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Open_BU4=([^/]]*)/])")]
        public string OpenBackup4Regex {
            get {
                return ((string)(this["OpenBackup4Regex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gun1=([0-9]+)")]
        public string Gun1Regex {
            get {
                return ((string)(this["Gun1Regex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gun2=([0-9]+)")]
        public string Gun2Regex {
            get {
                return ((string)(this["Gun2Regex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gun3=([0-9]+)")]
        public string Gun3Regex {
            get {
                return ((string)(this["Gun3Regex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gun4=([0-9]+)")]
        public string Gun4Regex {
            get {
                return ((string)(this["Gun4Regex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Eqlzr1=([^/]]*)/]")]
        public string Eqlzr1Regex {
            get {
                return ((string)(this["Eqlzr1Regex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Eqlzr2=([^/]]*)/]")]
        public string Eqlzr2Regex {
            get {
                return ((string)(this["Eqlzr2Regex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Eqlzr3=([^/]]*)/]")]
        public string Eqlzr3Regex {
            get {
                return ((string)(this["Eqlzr3Regex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Eqlzr4=([^/]]*)/]")]
        public string Eqlzr4Regex {
            get {
                return ((string)(this["Eqlzr4Regex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Anticip=([^/]]*)/]")]
        public string AnticpRegex {
            get {
                return ((string)(this["AnticpRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Gun1)")]
        public string IsSpotWeldKuka {
            get {
                return ((string)(this["IsSpotWeldKuka"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(ContCLS=\\[[X\\s]*\\]s*,\\s*ContOPN)")]
        public string IsServoWeldKuka {
            get {
                return ((string)(this["IsServoWeldKuka"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CASE +([0-9]+)\\s*[\\r\\n]+RUNSTYLE\\s+\\(#EXT_PGNR,#PGNR_ACKN,0\\s*\\)[\\r\\n]+([^\\)]+)")]
        public string STYLEPROGRAMREGEX {
            get {
                return ((string)(this["STYLEPROGRAMREGEX"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Call.Up *= *([^\\)]+)")]
        public string ProgramREGEX {
            get {
                return ((string)(this["ProgramREGEX"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TOOL_DATA\\[([\\d]+)\\]=\\{([^\\}]+)\\}")]
        public string ToolDataRegex {
            get {
                return ((string)(this["ToolDataRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(\\w{1}[1-6]?) ([\\d.-]+)")]
        public string KUKATOOLSPLIT {
            get {
                return ((string)(this["KUKATOOLSPLIT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DECL\\s+APPL_CONF\\s+(PROCESS[1-2]+)=\\{TECH\\s+\\#([^,]*)")]
        public string GetProcessRegex {
            get {
                return ((string)(this["GetProcessRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(";FOLD StdWld.[SPLTIN]+ [SG_]{1,3}([^, ]+),([^\\r]*)")]
        public string StudWeldRegex {
            get {
                return ((string)(this["StudWeldRegex"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vel:([0-9.-]*)")]
        public string StudVelocityRegex {
            get {
                return ((string)(this["StudVelocityRegex"]));
            }
            set {
                this["StudVelocityRegex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Schedule:([0-9]*)")]
        public string StudScheduleRegex {
            get {
                return ((string)(this["StudScheduleRegex"]));
            }
            set {
                this["StudScheduleRegex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select Root Directory for all robots")]
        public string SelectRootDirectory {
            get {
                return ((string)(this["SelectRootDirectory"]));
            }
            set {
                this["SelectRootDirectory"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("STYLE[0-9]+.LS")]
        public string FANUCMAINPROGRAMREGEX {
            get {
                return ((string)(this["FANUCMAINPROGRAMREGEX"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[0-9:]*L P\\[[0-9:;A-Z-a-z[;-]+]* [0-9]+mm/sec [^ ]* RTCP\\s;")]
        public string FanucStudRegex {
            get {
                return ((string)(this["FanucStudRegex"]));
            }
            set {
                this["FanucStudRegex"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("([0-9]+):[J|L]{1} +P\\[([0-9:1-z]+)\\] +([0-9]+)mm/sec +[0-9a-zA-Z]*[^:]*: *SPOT\\[S" +
            "D=([0-9]{1,2}),P=([0-9]{1,2}),S=([0-9]{1,2}),ED=([0-9]{1,2})\\] *;")]
        public string FANUCLINWELDREGEX {
            get {
                return ((string)(this["FANUCLINWELDREGEX"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[^!]CALL\\s+([^\\(]+)")]
        public string FANUCPROGRAMCALL {
            get {
                return ((string)(this["FANUCPROGRAMCALL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".LS")]
        public string FANUCEXTENSION {
            get {
                return ((string)(this["FANUCEXTENSION"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("([0-9]+):[J|L]{1} +P\\[([0-9:1-z]+)\\] +([0-9]+)mm/sec +[0-9a-zA-Z]*[^:]*: *SPOT\\[S" +
            "D=([0-9]{1,2}),P=([0-9]{1,2}),S=([0-9]{1,2}),(ED=[0-9]{1,2})\\] *;")]
        public string FANUCPTPWELDREGEX {
            get {
                return ((string)(this["FANUCPTPWELDREGEX"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PROG +S([0-9]+)")]
        public string FANUCSTYLEFROMPROGRAMREGEX {
            get {
                return ((string)(this["FANUCSTYLEFROMPROGRAMREGEX"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".SRC")]
        public string KUKAEXTENSION {
            get {
                return ((string)(this["KUKAEXTENSION"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[^0-9]([0-9]+)")]
        public string STYLEEXTRACTREGEX {
            get {
                return ((string)(this["STYLEEXTRACTREGEX"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Resources\\Parameters.xml")]
        public string ParametersFile {
            get {
                return ((string)(this["ParametersFile"]));
            }
            set {
                this["ParametersFile"] = value;
            }
        }
    }
}
