//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetWelds.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LabelResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LabelResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GetWelds.Resources.LabelResources", typeof(LabelResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string B {
            get {
                return ResourceManager.GetString("B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        public static string C {
            get {
                return ResourceManager.GetString("C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Filename to export files to.
        /// </summary>
        public static string ExportFilesMessage {
            get {
                return ResourceManager.GetString("ExportFilesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression.
        /// </summary>
        public static string Expression {
            get {
                return ResourceManager.GetString("Expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename Written as filter.
        ///i.e. *.TP, *.*, Definer.TP.
        /// </summary>
        public static string FileFilter {
            get {
                return ResourceManager.GetString("FileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        public static string Filename {
            get {
                return ResourceManager.GetString("Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Joint Regex Here.
        /// </summary>
        public static string JointNameWatermark {
            get {
                return ResourceManager.GetString("JointNameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joint.
        /// </summary>
        public static string JointString {
            get {
                return ResourceManager.GetString("JointString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Linear Regex Here.
        /// </summary>
        public static string LinearNameWatermark {
            get {
                return ResourceManager.GetString("LinearNameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear.
        /// </summary>
        public static string LinearString {
            get {
                return ResourceManager.GetString("LinearString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Search Parameter file to load..
        /// </summary>
        public static string LoadSearchParameterDialog {
            get {
                return ResourceManager.GetString("LoadSearchParameterDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Search Parameters.
        /// </summary>
        public static string LoadSearchParameters {
            get {
                return ResourceManager.GetString("LoadSearchParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Xml file from computer..
        /// </summary>
        public static string LoadXml {
            get {
                return ResourceManager.GetString("LoadXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Nutweld Regex Here.
        /// </summary>
        public static string NutweldNameWatermark {
            get {
                return ResourceManager.GetString("NutweldNameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutweld.
        /// </summary>
        public static string NutWeldString {
            get {
                return ResourceManager.GetString("NutWeldString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        public static string P {
            get {
                return ResourceManager.GetString("P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positions.
        /// </summary>
        public static string Positions {
            get {
                return ResourceManager.GetString("Positions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process 1.
        /// </summary>
        public static string Process1 {
            get {
                return ResourceManager.GetString("Process1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process 2.
        /// </summary>
        public static string Process2 {
            get {
                return ResourceManager.GetString("Process2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        public static string R {
            get {
                return ResourceManager.GetString("R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Rivet Regex Here.
        /// </summary>
        public static string RivetNameWatermark {
            get {
                return ResourceManager.GetString("RivetNameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rivet.
        /// </summary>
        public static string RivetString {
            get {
                return ResourceManager.GetString("RivetString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot Options.
        /// </summary>
        public static string RobotOptions {
            get {
                return ResourceManager.GetString("RobotOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file to save search parameters to.
        /// </summary>
        public static string SaveSearchParameterDialog {
            get {
                return ResourceManager.GetString("SaveSearchParameterDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Search Parameters.
        /// </summary>
        public static string SaveSearchParameters {
            get {
                return ResourceManager.GetString("SaveSearchParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Xml configuration to computer..
        /// </summary>
        public static string SaveXml {
            get {
                return ResourceManager.GetString("SaveXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Parameters.
        /// </summary>
        public static string SearchParameters {
            get {
                return ResourceManager.GetString("SearchParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters for search expression in regex format.
        /// </summary>
        public static string SearchParamExpressionTooltip {
            get {
                return ResourceManager.GetString("SearchParamExpressionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Parameter File (*.xml)|*.xml.
        /// </summary>
        public static string SearchParamFilter {
            get {
                return ResourceManager.GetString("SearchParamFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value in string format on how you would like result to be returned.
        /// </summary>
        public static string SearchParamValueTooltip {
            get {
                return ResourceManager.GetString("SearchParamValueTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Servoweld Regex Here.
        /// </summary>
        public static string ServoweldnameWatermark {
            get {
                return ResourceManager.GetString("ServoweldnameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servoweld.
        /// </summary>
        public static string ServoWeldString {
            get {
                return ResourceManager.GetString("ServoWeldString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Stud Regex Here.
        /// </summary>
        public static string StudNameWatermark {
            get {
                return ResourceManager.GetString("StudNameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stud.
        /// </summary>
        public static string StudString {
            get {
                return ResourceManager.GetString("StudString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style Name.
        /// </summary>
        public static string StyleName {
            get {
                return ResourceManager.GetString("StyleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Style Regex Here.
        /// </summary>
        public static string StyleNameWatermark {
            get {
                return ResourceManager.GetString("StyleNameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles.
        /// </summary>
        public static string Styles {
            get {
                return ResourceManager.GetString("Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Data.
        /// </summary>
        public static string ToolData {
            get {
                return ResourceManager.GetString("ToolData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        public static string W {
            get {
                return ResourceManager.GetString("W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welds.
        /// </summary>
        public static string Welds {
            get {
                return ResourceManager.GetString("Welds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        public static string X {
            get {
                return ResourceManager.GetString("X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        public static string Y {
            get {
                return ResourceManager.GetString("Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z.
        /// </summary>
        public static string Z {
            get {
                return ResourceManager.GetString("Z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zones.
        /// </summary>
        public static string Zones {
            get {
                return ResourceManager.GetString("Zones", resourceCulture);
            }
        }
    }
}
